// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexico.jflex

package olc1.proyecto1.pkg202307793;
import java_cup.runtime.*;
import java.util.LinkedList;
import Clases.token; 
import Clases.errorLexico;

@SuppressWarnings("fallthrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\2\22\0\1\1\1\4"+
    "\1\5\1\6\2\0\1\7\1\0\1\10\1\11\1\12"+
    "\1\0\1\13\1\0\1\14\1\0\12\15\1\16\1\17"+
    "\1\20\1\21\1\22\2\0\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\32\1\35"+
    "\1\32\1\36\1\37\1\40\1\32\1\41\1\42\1\43"+
    "\1\44\2\32\1\45\1\46\1\32\1\47\1\50\1\51"+
    "\1\0\1\32\1\0\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\32\1\35\1\32"+
    "\1\36\1\37\1\40\1\32\1\41\1\42\1\43\1\44"+
    "\2\32\1\45\1\46\1\32\1\52\1\53\1\54\7\0"+
    "\1\3\252\0\2\55\115\0\1\56\u01a8\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\3\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\16\15\1\16"+
    "\1\17\1\20\1\1\1\21\2\1\1\22\1\0\1\23"+
    "\1\0\1\24\1\0\1\25\1\0\1\26\1\27\1\30"+
    "\2\15\1\31\7\15\1\0\12\15\1\0\1\32\5\0"+
    "\1\33\1\34\11\15\2\0\1\35\3\15\1\36\5\15"+
    "\2\37\1\35\1\36\2\0\1\40\1\0\1\15\1\41"+
    "\4\15\1\0\3\15\2\0\1\42\1\15\1\43\2\15"+
    "\1\0\1\15\1\44\1\15\1\0\1\45\1\46\2\15"+
    "\2\47\2\15\1\50\2\0\1\15\1\51\1\15\1\0"+
    "\1\52\1\15\1\51\1\15\1\53\2\54\2\55\1\56"+
    "\2\57\1\60\1\15\1\0\2\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\215\0\274\0\353\0\57"+
    "\0\57\0\57\0\u011a\0\57\0\57\0\u0149\0\u0178\0\u01a7"+
    "\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f"+
    "\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a\0\u0439\0\57\0\57"+
    "\0\57\0\u0468\0\57\0\u0497\0\u04c6\0\57\0\215\0\57"+
    "\0\u04f5\0\u0524\0\u0553\0\57\0\u0582\0\57\0\57\0\57"+
    "\0\u05b1\0\u05e0\0\u02f0\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb"+
    "\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843"+
    "\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\57\0\u098c"+
    "\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0582\0\u02f0\0\u0a77\0\u0aa6"+
    "\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e"+
    "\0\u0c4d\0\u02f0\0\u0c7c\0\u0cab\0\u0cda\0\u02f0\0\u0d09\0\u0d38"+
    "\0\u0d67\0\u0d96\0\u0dc5\0\u02f0\0\57\0\57\0\57\0\u0df4"+
    "\0\u0e23\0\u0a48\0\u0e52\0\u0e81\0\u02f0\0\u0eb0\0\u0edf\0\u0f0e"+
    "\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u02f0"+
    "\0\u1086\0\u02f0\0\u10b5\0\u10e4\0\u1113\0\u1142\0\u02f0\0\u1171"+
    "\0\u11a0\0\u02f0\0\u02f0\0\u11cf\0\u11fe\0\u02f0\0\57\0\u122d"+
    "\0\u125c\0\u02f0\0\u128b\0\u12ba\0\u12e9\0\u02f0\0\u1318\0\u1347"+
    "\0\u02f0\0\u1376\0\57\0\u13a5\0\u02f0\0\u02f0\0\57\0\u02f0"+
    "\0\57\0\u02f0\0\u02f0\0\57\0\u02f0\0\u13d4\0\u1403\0\u02f0"+
    "\0\57";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\2\1\12\1\2\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\2\27\1\30\2\27\1\31\1\32\1\27\1\33\1\34"+
    "\1\35\1\36\2\27\1\37\1\2\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\100\0\1\46\35\0\5\47\1\50"+
    "\42\47\1\51\6\47\6\0\1\52\3\0\1\53\53\0"+
    "\1\54\63\0\1\55\1\13\62\0\1\56\56\0\1\57"+
    "\56\0\1\60\52\0\1\27\5\0\3\27\1\61\12\27"+
    "\1\62\1\27\1\63\3\27\25\0\1\27\5\0\14\27"+
    "\1\64\7\27\25\0\1\27\5\0\12\27\1\65\11\27"+
    "\25\0\1\27\5\0\1\66\23\27\25\0\1\27\5\0"+
    "\22\27\1\67\1\27\25\0\1\27\5\0\1\70\7\27"+
    "\1\71\1\27\1\72\11\27\6\0\1\73\16\0\1\27"+
    "\5\0\24\27\25\0\1\27\5\0\13\27\1\74\10\27"+
    "\25\0\1\27\5\0\21\27\1\75\2\27\25\0\1\27"+
    "\5\0\1\27\1\76\22\27\25\0\1\27\5\0\4\27"+
    "\1\77\17\27\25\0\1\27\5\0\4\27\1\100\13\27"+
    "\1\101\3\27\25\0\1\27\5\0\1\102\15\27\1\103"+
    "\5\27\25\0\1\27\5\0\15\27\1\104\1\27\1\105"+
    "\4\27\7\0\1\106\53\0\1\107\41\0\1\110\47\0"+
    "\1\111\13\0\1\112\13\0\2\47\2\0\53\47\2\52"+
    "\2\0\53\52\6\53\1\113\3\53\1\114\44\53\15\0"+
    "\1\115\56\0\1\27\5\0\3\27\1\116\20\27\25\0"+
    "\1\27\5\0\16\27\1\117\5\27\25\0\1\27\5\0"+
    "\14\27\1\120\7\27\25\0\1\27\5\0\4\27\1\121"+
    "\17\27\25\0\1\27\5\0\20\27\1\122\3\27\25\0"+
    "\1\27\5\0\15\27\1\123\6\27\25\0\1\27\5\0"+
    "\12\27\1\124\11\27\25\0\1\27\5\0\4\27\1\125"+
    "\5\27\1\126\11\27\25\0\1\27\5\0\14\27\1\127"+
    "\7\27\37\0\1\130\5\0\1\131\36\0\1\27\5\0"+
    "\20\27\1\132\3\27\25\0\1\27\5\0\12\27\1\133"+
    "\11\27\25\0\1\27\5\0\11\27\1\134\12\27\25\0"+
    "\1\27\5\0\1\135\23\27\25\0\1\27\5\0\20\27"+
    "\1\136\3\27\25\0\1\27\5\0\14\27\1\137\1\27"+
    "\1\140\5\27\25\0\1\27\5\0\1\27\1\141\22\27"+
    "\25\0\1\27\5\0\21\27\1\142\2\27\25\0\1\27"+
    "\5\0\3\27\1\143\20\27\25\0\1\27\5\0\4\27"+
    "\1\144\17\27\37\0\1\145\72\0\1\146\56\0\1\147"+
    "\52\0\1\150\1\0\1\151\15\0\6\53\1\113\3\53"+
    "\1\152\52\53\1\0\3\53\1\153\44\53\15\0\1\27"+
    "\5\0\1\154\23\27\25\0\1\27\5\0\12\27\1\155"+
    "\11\27\25\0\1\27\5\0\1\156\23\27\25\0\1\27"+
    "\5\0\1\157\23\27\25\0\1\27\5\0\14\27\1\160"+
    "\7\27\25\0\1\27\5\0\17\27\1\161\4\27\7\0"+
    "\1\162\15\0\1\27\5\0\12\27\1\163\11\27\25\0"+
    "\1\27\5\0\20\27\1\164\3\27\25\0\1\27\5\0"+
    "\1\165\23\27\45\0\1\166\64\0\1\167\30\0\1\27"+
    "\5\0\12\27\1\170\11\27\25\0\1\27\5\0\4\27"+
    "\1\171\17\27\25\0\1\27\5\0\3\27\1\172\20\27"+
    "\25\0\1\27\5\0\16\27\1\173\5\27\25\0\1\27"+
    "\5\0\10\27\1\174\13\27\6\0\1\175\16\0\1\27"+
    "\5\0\12\27\1\176\11\27\25\0\1\27\5\0\4\27"+
    "\1\177\17\27\25\0\1\27\5\0\1\200\23\27\51\0"+
    "\1\201\50\0\1\175\21\0\1\175\1\0\6\53\1\113"+
    "\3\53\1\153\44\53\15\0\1\27\5\0\23\27\1\202"+
    "\25\0\1\27\5\0\16\27\1\203\5\27\25\0\1\27"+
    "\5\0\1\27\1\204\22\27\25\0\1\27\5\0\16\27"+
    "\1\205\5\27\25\0\1\27\5\0\4\27\1\206\17\27"+
    "\37\0\1\207\44\0\1\27\5\0\3\27\1\210\20\27"+
    "\25\0\1\27\5\0\4\27\1\211\17\27\25\0\1\27"+
    "\5\0\20\27\1\212\3\27\36\0\1\213\57\0\1\214"+
    "\44\0\1\27\5\0\2\27\1\215\21\27\25\0\1\27"+
    "\5\0\4\27\1\216\17\27\25\0\1\27\5\0\13\27"+
    "\1\217\10\27\46\0\1\220\35\0\1\27\5\0\4\27"+
    "\1\221\17\27\25\0\1\27\5\0\20\27\1\222\3\27"+
    "\37\0\1\223\44\0\1\27\5\0\1\224\23\27\25\0"+
    "\1\27\5\0\20\27\1\225\3\27\25\0\1\27\5\0"+
    "\17\27\1\226\4\27\7\0\1\227\15\0\1\27\5\0"+
    "\16\27\1\230\5\27\52\0\1\227\13\0\1\227\41\0"+
    "\1\231\32\0\1\27\5\0\20\27\1\232\3\27\25\0"+
    "\1\27\5\0\6\27\1\233\15\27\41\0\1\234\42\0"+
    "\1\27\5\0\4\27\1\235\17\27\25\0\1\27\5\0"+
    "\17\27\1\236\4\27\7\0\1\237\15\0\1\27\5\0"+
    "\4\27\1\240\17\27\37\0\1\241\27\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5170];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\4\1\3\11\1\1\2\11\21\1\3\11"+
    "\1\1\1\11\2\1\1\11\1\0\1\11\1\0\1\1"+
    "\1\0\1\11\1\0\3\11\12\1\1\0\12\1\1\0"+
    "\1\11\5\0\13\1\2\0\13\1\3\11\2\0\1\1"+
    "\1\0\6\1\1\0\3\1\2\0\5\1\1\0\3\1"+
    "\1\0\5\1\1\11\3\1\2\0\3\1\1\0\2\1"+
    "\1\11\3\1\1\11\1\1\1\11\2\1\1\11\2\1"+
    "\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    LinkedList<errorLexico> listaErrores = new LinkedList<>();
    LinkedList<token> listaTokens = new LinkedList<>();
    public LinkedList<token> getTokens() {
        return listaTokens;
    }

    public LinkedList<errorLexico> getErrores() {
        return listaErrores;
    }

    public void limpiarListas() {
        listaTokens.clear();
        listaErrores.clear();
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
      yyline = 1;
    yychar = 1;
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errorLexico e = new errorLexico(yytext(), (int)yyline, (int)yychar, "Símbolo no reconocido");
    listaErrores.add(e);
    System.out.println(
        "Error Léxico: " + yytext() +
        " en línea: " + yyline +
        " columna: " + yychar
    );
            }
          // fall through
          case 50: break;
          case 2:
            { 
            }
          // fall through
          case 51: break;
          case 3:
            { token t = new token("NOT", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Operador lógico NOT reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.NOT, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 52: break;
          case 4:
            { token t = new token("PARIZQ", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Simbolo reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.PARIZQ, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 53: break;
          case 5:
            { token t = new token("PARDER", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Simbolo reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.PARDER, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 54: break;
          case 6:
            { token t = new token("COMA", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Simbolo reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.COMA, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 55: break;
          case 7:
            { token t = new token("ENTERO", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Token reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.ENTERO, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 56: break;
          case 8:
            { token t = new token("DOSPUNTOS", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Simbolo reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.DOSPUNTOS, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 57: break;
          case 9:
            { token t = new token("PTCOMA", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Simbolo reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.PTCOMA, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 58: break;
          case 10:
            { token t = new token("MENOR", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Operador reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.MENOR, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 59: break;
          case 11:
            { token t = new token("IGUAL_SIMPLE", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Operador reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.IGUAL_SIMPLE, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 60: break;
          case 12:
            { token t = new token("MAYOR", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Operador reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.MAYOR, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 61: break;
          case 13:
            { token t = new token("ID", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Identificador reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.ID, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 62: break;
          case 14:
            { token t = new token("CORIZQ", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Simbolo reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.CORIZQ, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 63: break;
          case 15:
            { token t = new token("CORDER", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Simbolo reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.CORDER, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 64: break;
          case 16:
            { token t = new token("LLAIZQ", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Simbolo reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.LLAIZQ, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 65: break;
          case 17:
            { token t = new token("LLADER", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Simbolo reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.LLADER, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 66: break;
          case 18:
            { token t = new token("DIFERENTE", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Operador reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.DIFERENTE, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 67: break;
          case 19:
            { token t = new token("STRING_LITERAL", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Cadena reconocida: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.STRING_LITERAL, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 68: break;
          case 20:
            { System.out.println("Comentario de una línea (esto será ignorado): " + yytext());
    // no devolvemos token al parser
    /* skip */
            }
          // fall through
          case 69: break;
          case 21:
            { token t = new token("AND", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Operador lógico AND reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.AND, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 70: break;
          case 22:
            { token t = new token("MENORIGUAL", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Operador reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.MENORIGUAL, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 71: break;
          case 23:
            { token t = new token("IGUAL", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Operador reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.IGUAL, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 72: break;
          case 24:
            { token t = new token("MAYORIGUAL", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Operador reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.MAYORIGUAL, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 73: break;
          case 25:
            { token t = new token("AT", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.AT, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 74: break;
          case 26:
            { token t = new token("OR", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Operador lógico OR reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.OR, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 75: break;
          case 27:
            { token t = new token("DECIMAL", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Token reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.DECIMAL, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 76: break;
          case 28:
            { token t = new token("ADD", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.ADD, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 77: break;
          case 29:
            { token t = new token("INT", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.INT, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 78: break;
          case 30:
            { token t = new token("SET", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.SET, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 79: break;
          case 31:
            { token t = new token("USE", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.USE, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 80: break;
          case 32:
            { System.out.println("Comentario multilínea (esto será ignorado): " + yytext());
    // no devolvemos token al parser
    /* skip */
            }
          // fall through
          case 81: break;
          case 33:
            { token t = new token("BOOL", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.BOOL, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 82: break;
          case 34:
            { token t = new token("NULL", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.NULL, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 83: break;
          case 35:
            { token t = new token("READ", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.READ, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 84: break;
          case 36:
            { token t = new token("TRUE", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Booleano TRUE reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.TRUE, (int)yyline, (int)yychar, Boolean.TRUE);
            }
          // fall through
          case 85: break;
          case 37:
            { token t = new token("ARRAY", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.ARRAY, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 86: break;
          case 38:
            { token t = new token("CLEAR", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.CLEAR, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 87: break;
          case 39:
            { token t = new token("FALSE", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Booleano FALSE reconocido: " + yyline + " - " + yychar + " -> " + yytext());
    return new Symbol(sym.FALSE, (int)yyline, (int)yychar, Boolean.FALSE);
            }
          // fall through
          case 88: break;
          case 40:
            { token t = new token("FLOAT", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.FLOAT, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 89: break;
          case 41:
            { token t = new token("STORE", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.STORE, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 90: break;
          case 42:
            { token t = new token("TABLE", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.TABLE, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 91: break;
          case 43:
            { token t = new token("EXPORT", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.EXPORT, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 92: break;
          case 44:
            { token t = new token("FIELDS", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.FIELDS, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 93: break;
          case 45:
            { token t = new token("FILTER", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.FILTER, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 94: break;
          case 46:
            { token t = new token("OBJECT", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.OBJECT, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 95: break;
          case 47:
            { token t = new token("STRING", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.STRING, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 96: break;
          case 48:
            { token t = new token("UPDATE", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->> " + yytext());
    return new Symbol(sym.UPDATE, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 97: break;
          case 49:
            { token t = new token("DATABASE", yytext(), (int)yyline, (int)yychar);
    listaTokens.add(t);
    System.out.println("Palabra reservada reconocida: " + yyline + " - " + yychar + " ->< " + yytext());
    return new Symbol(sym.DATABASE, (int)yyline, (int)yychar, yytext());
            }
          // fall through
          case 98: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
