
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package olc1.proyecto1.pkg202307793;

import java_cup.runtime.*;
import java.util.*;
import com.google.gson.Gson;
import java.io.FileWriter;
import java.io.IOException;
import Clases.camposInfo;
import Clases.filtroInfo;
import Clases.lecturaInfo;
import Clases.actualizacionInfo;
import Clases.gestorBD;
import java.util.LinkedList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\107\000\002\002\004\000\002\002\003\000\002\004" +
    "\004\000\002\004\003\000\002\003\003\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\003\000\002\003\003\000\002" +
    "\005\007\000\002\006\006\000\002\007\005\000\002\010" +
    "\007\000\002\011\004\000\002\011\003\000\002\012\006" +
    "\000\002\013\003\000\002\013\003\000\002\013\003\000" +
    "\002\013\003\000\002\013\003\000\002\013\003\000\002" +
    "\013\003\000\002\014\010\000\002\015\004\000\002\015" +
    "\003\000\002\016\006\000\002\017\004\000\002\020\005" +
    "\000\002\020\002\000\002\021\010\000\002\021\010\000" +
    "\002\021\010\000\002\021\010\000\002\021\010\000\002" +
    "\021\010\000\002\022\005\000\002\023\010\000\002\024" +
    "\004\000\002\025\005\000\002\025\002\000\002\026\005" +
    "\000\002\027\003\000\002\027\003\000\002\027\003\000" +
    "\002\027\003\000\002\027\003\000\002\027\003\000\002" +
    "\027\005\000\002\027\005\000\002\030\004\000\002\031" +
    "\005\000\002\031\002\000\002\032\010\000\002\033\004" +
    "\000\002\033\003\000\002\034\006\000\002\035\004\000" +
    "\002\036\005\000\002\036\002\000\002\037\005\000\002" +
    "\040\010\000\002\040\010\000\002\040\010\000\002\040" +
    "\010\000\002\040\010\000\002\040\010\000\002\041\005" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\240\000\022\041\020\042\023\043\015\044\004\051" +
    "\024\052\021\053\026\055\005\001\002\000\004\026\176" +
    "\001\002\000\004\026\174\001\002\000\024\002\ufffb\041" +
    "\ufffb\042\ufffb\043\ufffb\044\ufffb\051\ufffb\052\ufffb\053\ufffb" +
    "\055\ufffb\001\002\000\024\002\ufffe\041\020\042\023\043" +
    "\015\044\004\051\024\052\021\053\026\055\005\001\002" +
    "\000\024\002\ufff8\041\ufff8\042\ufff8\043\ufff8\044\ufff8\051" +
    "\ufff8\052\ufff8\053\ufff8\055\ufff8\001\002\000\004\002\000" +
    "\001\002\000\024\002\ufffc\041\ufffc\042\ufffc\043\ufffc\044" +
    "\ufffc\051\ufffc\052\ufffc\053\ufffc\055\ufffc\001\002\000\004" +
    "\002\172\001\002\000\024\002\ufff7\041\ufff7\042\ufff7\043" +
    "\ufff7\044\ufff7\051\ufff7\052\ufff7\053\ufff7\055\ufff7\001\002" +
    "\000\004\026\151\001\002\000\024\002\ufff9\041\ufff9\042" +
    "\ufff9\043\ufff9\044\ufff9\051\ufff9\052\ufff9\053\ufff9\055\ufff9" +
    "\001\002\000\024\002\ufffd\041\ufffd\042\ufffd\043\ufffd\044" +
    "\ufffd\051\ufffd\052\ufffd\053\ufffd\055\ufffd\001\002\000\004" +
    "\026\141\001\002\000\004\026\134\001\002\000\024\002" +
    "\ufffa\041\ufffa\042\ufffa\043\ufffa\044\ufffa\051\ufffa\052\ufffa" +
    "\053\ufffa\055\ufffa\001\002\000\004\026\132\001\002\000" +
    "\004\027\130\001\002\000\024\002\ufff6\041\ufff6\042\ufff6" +
    "\043\ufff6\044\ufff6\051\ufff6\052\ufff6\053\ufff6\055\ufff6\001" +
    "\002\000\004\026\027\001\002\000\004\011\030\001\002" +
    "\000\004\054\033\001\002\000\006\012\uffc7\046\102\001" +
    "\002\000\004\012\100\001\002\000\004\057\034\001\002" +
    "\000\004\026\035\001\002\000\004\060\045\001\002\000" +
    "\004\004\044\001\002\000\006\004\uffc3\056\040\001\002" +
    "\000\004\026\035\001\002\000\004\004\uffc5\001\002\000" +
    "\006\004\uffc3\056\040\001\002\000\004\004\uffc4\001\002" +
    "\000\006\012\uffc6\046\uffc6\001\002\000\022\007\047\011" +
    "\056\024\050\025\046\027\054\030\051\031\055\040\053" +
    "\001\002\000\012\004\uffd3\010\uffd3\012\uffd3\056\uffd3\001" +
    "\002\000\022\007\047\011\056\024\050\025\046\027\054" +
    "\030\051\031\055\040\053\001\002\000\012\004\uffd4\010" +
    "\uffd4\012\uffd4\056\uffd4\001\002\000\012\004\uffd1\010\uffd1" +
    "\012\uffd1\056\uffd1\001\002\000\006\004\uffc2\056\uffc2\001" +
    "\002\000\012\004\uffcf\010\uffcf\012\uffcf\056\uffcf\001\002" +
    "\000\012\004\uffd2\010\uffd2\012\uffd2\056\uffd2\001\002\000" +
    "\012\004\uffd0\010\uffd0\012\uffd0\056\uffd0\001\002\000\004" +
    "\026\057\001\002\000\004\057\067\001\002\000\004\012" +
    "\066\001\002\000\006\012\uffd6\056\062\001\002\000\004" +
    "\026\057\001\002\000\004\012\uffd8\001\002\000\006\012" +
    "\uffd6\056\062\001\002\000\004\012\uffd7\001\002\000\012" +
    "\004\uffcd\010\uffcd\012\uffcd\056\uffcd\001\002\000\022\007" +
    "\047\011\056\024\050\025\046\027\054\030\051\031\055" +
    "\040\053\001\002\000\006\012\uffd5\056\uffd5\001\002\000" +
    "\006\010\uffca\056\074\001\002\000\004\010\073\001\002" +
    "\000\012\004\uffce\010\uffce\012\uffce\056\uffce\001\002\000" +
    "\022\007\047\011\056\024\050\025\046\027\054\030\051" +
    "\031\055\040\053\001\002\000\004\010\uffcc\001\002\000" +
    "\006\010\uffca\056\074\001\002\000\004\010\uffcb\001\002" +
    "\000\004\004\101\001\002\000\024\002\uffc9\041\uffc9\042" +
    "\uffc9\043\uffc9\044\uffc9\051\uffc9\052\uffc9\053\uffc9\055\uffc9" +
    "\001\002\000\004\057\104\001\002\000\004\012\uffc8\001" +
    "\002\000\004\026\105\001\002\000\016\013\110\014\111" +
    "\015\113\016\112\017\106\020\107\001\002\000\022\007" +
    "\047\011\056\024\050\025\046\027\054\030\051\031\055" +
    "\040\053\001\002\000\022\007\047\011\056\024\050\025" +
    "\046\027\054\030\051\031\055\040\053\001\002\000\022" +
    "\007\047\011\056\024\050\025\046\027\054\030\051\031" +
    "\055\040\053\001\002\000\022\007\047\011\056\024\050" +
    "\025\046\027\054\030\051\031\055\040\053\001\002\000" +
    "\022\007\047\011\056\024\050\025\046\027\054\030\051" +
    "\031\055\040\053\001\002\000\022\007\047\011\056\024" +
    "\050\025\046\027\054\030\051\031\055\040\053\001\002" +
    "\000\004\004\115\001\002\000\004\012\uffbf\001\002\000" +
    "\004\004\117\001\002\000\004\012\uffbe\001\002\000\004" +
    "\004\121\001\002\000\004\012\uffc0\001\002\000\004\004" +
    "\123\001\002\000\004\012\uffc1\001\002\000\004\004\125" +
    "\001\002\000\004\012\uffbc\001\002\000\004\004\127\001" +
    "\002\000\004\012\uffbd\001\002\000\004\004\131\001\002" +
    "\000\024\002\uffda\041\uffda\042\uffda\043\uffda\044\uffda\051" +
    "\uffda\052\uffda\053\uffda\055\uffda\001\002\000\004\004\133" +
    "\001\002\000\024\002\ufff3\041\ufff3\042\ufff3\043\ufff3\044" +
    "\ufff3\051\ufff3\052\ufff3\053\ufff3\055\ufff3\001\002\000\004" +
    "\011\135\001\002\000\004\026\057\001\002\000\004\012" +
    "\137\001\002\000\004\004\140\001\002\000\024\002\uffd9" +
    "\041\uffd9\042\uffd9\043\uffd9\044\uffd9\051\uffd9\052\uffd9\053" +
    "\uffd9\055\uffd9\001\002\000\004\011\142\001\002\000\004" +
    "\047\144\001\002\000\004\012\150\001\002\000\004\050" +
    "\145\001\002\000\004\027\146\001\002\000\004\004\147" +
    "\001\002\000\004\012\ufff4\001\002\000\024\002\ufff5\041" +
    "\ufff5\042\ufff5\043\ufff5\044\ufff5\051\ufff5\052\ufff5\053\ufff5" +
    "\055\ufff5\001\002\000\004\011\152\001\002\000\004\026" +
    "\153\001\002\000\004\057\160\001\002\000\004\012\157" +
    "\001\002\000\006\012\ufff0\026\153\001\002\000\004\012" +
    "\ufff1\001\002\000\024\002\ufff2\041\ufff2\042\ufff2\043\ufff2" +
    "\044\ufff2\051\ufff2\052\ufff2\053\ufff2\055\ufff2\001\002\000" +
    "\020\032\170\033\166\034\164\035\161\036\167\037\162" +
    "\040\163\001\002\000\004\004\uffeb\001\002\000\004\004" +
    "\uffe9\001\002\000\004\004\uffe8\001\002\000\004\004\uffec" +
    "\001\002\000\004\004\171\001\002\000\004\004\uffed\001" +
    "\002\000\004\004\uffea\001\002\000\004\004\uffee\001\002" +
    "\000\006\012\uffef\026\uffef\001\002\000\004\002\001\001" +
    "\002\000\004\002\uffff\001\002\000\004\004\175\001\002" +
    "\000\024\002\uffbb\041\uffbb\042\uffbb\043\uffbb\044\uffbb\051" +
    "\uffbb\052\uffbb\053\uffbb\055\uffbb\001\002\000\004\011\177" +
    "\001\002\000\004\045\201\001\002\000\006\012\uffe5\046" +
    "\215\001\002\000\004\057\205\001\002\000\004\012\203" +
    "\001\002\000\004\004\204\001\002\000\024\002\uffe7\041" +
    "\uffe7\042\uffe7\043\uffe7\044\uffe7\051\uffe7\052\uffe7\053\uffe7" +
    "\055\uffe7\001\002\000\004\026\206\001\002\000\006\004" +
    "\uffe1\056\211\001\002\000\004\004\210\001\002\000\006" +
    "\012\uffe4\046\uffe4\001\002\000\004\026\213\001\002\000" +
    "\004\004\uffe3\001\002\000\006\004\uffe1\056\211\001\002" +
    "\000\004\004\uffe2\001\002\000\004\057\217\001\002\000" +
    "\004\012\uffe6\001\002\000\004\026\220\001\002\000\016" +
    "\013\223\014\224\015\226\016\225\017\222\020\221\001" +
    "\002\000\022\007\047\011\056\024\050\025\046\027\054" +
    "\030\051\031\055\040\053\001\002\000\022\007\047\011" +
    "\056\024\050\025\046\027\054\030\051\031\055\040\053" +
    "\001\002\000\022\007\047\011\056\024\050\025\046\027" +
    "\054\030\051\031\055\040\053\001\002\000\022\007\047" +
    "\011\056\024\050\025\046\027\054\030\051\031\055\040" +
    "\053\001\002\000\022\007\047\011\056\024\050\025\046" +
    "\027\054\030\051\031\055\040\053\001\002\000\022\007" +
    "\047\011\056\024\050\025\046\027\054\030\051\031\055" +
    "\040\053\001\002\000\004\004\230\001\002\000\004\012" +
    "\uffde\001\002\000\004\004\232\001\002\000\004\012\uffdd" +
    "\001\002\000\004\004\234\001\002\000\004\012\uffdf\001" +
    "\002\000\004\004\236\001\002\000\004\012\uffe0\001\002" +
    "\000\004\004\240\001\002\000\004\012\uffdc\001\002\000" +
    "\004\004\242\001\002\000\004\012\uffdb\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\240\000\030\002\012\003\006\004\010\005\016\007" +
    "\011\010\005\014\021\022\024\023\015\032\007\041\013" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\026\003\006\004\172\005\016\007\011\010\005" +
    "\014\021\022\024\023\015\032\007\041\013\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\033\031\034\030\001\001\000\004\040\102\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\035\035\037\036" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\036" +
    "\040\001\001\000\004\037\041\001\001\000\002\001\001" +
    "\000\004\036\042\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\027\051\001\001\000\002\001\001\000\006" +
    "\027\070\030\071\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\024\057\026\060\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\025\062\001\001" +
    "\000\004\026\063\001\001\000\002\001\001\000\004\025" +
    "\064\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\027\067\001\001\000\002\001\001\000\004\031\074\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\027\075" +
    "\001\001\000\002\001\001\000\004\031\076\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\027\125\001\001\000\004\027\123\001\001" +
    "\000\004\027\121\001\001\000\004\027\117\001\001\000" +
    "\004\027\115\001\001\000\004\027\113\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\024\135\026\060\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\006\142\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\011\153\012\154" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\011" +
    "\155\012\154\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\013\164\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\015" +
    "\201\016\177\001\001\000\004\021\215\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\017\206\001\001\000\004\020\211\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\020\213\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\027\240\001\001\000\004\027\236" +
    "\001\001\000\004\027\234\001\001\000\004\027\232\001" +
    "\001\000\004\027\230\001\001\000\004\027\226\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Declaramos el gestor de la BD
    public static gestorBD gestor = new gestorBD();
 // Lista para acumular errores sintácticos
    public java.util.LinkedList<String> erroresSintacticos = new java.util.LinkedList<>();

    // Manejo de errores mejorado
    public void report_error(String message, Object info) {
        System.err.println("ERROR SINTÁCTICO: " + message);
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = (java_cup.runtime.Symbol) info;
            String error = "Error sintáctico en línea: " + s.left + 
                         " columna: " + s.right + 
                         " token: " + sym.terminalNames[s.sym];
            erroresSintacticos.add(error);
            System.err.println(error);
        }
    }

    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
    }


     //Códgio para tener en cuenta las funciones que realizamos
        public java.util.LinkedList<String> mensajes = new java.util.LinkedList<>();


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintactico$actions {
  private final Sintactico parser;

  /** Constructor */
  CUP$Sintactico$actions(Sintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action_part00000000(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico$parser.done_parsing();
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= listaInstrucciones 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // listaInstrucciones ::= instruccion listaInstrucciones 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("listaInstrucciones",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // listaInstrucciones ::= instruccion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("listaInstrucciones",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion ::= definicionDB 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= instruccionUse 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= definicionTabla 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instruccion ::= lectura 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instruccion ::= insercion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instruccion ::= actualizacion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion ::= eliminacion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // instruccion ::= exportacion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // definicionDB ::= DATABASE ID LLAIZQ storeDecl LLADER 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
        gestor.crearBaseDeDatos(nombre, s);
        System.out.println("Definición de base de datos: " + nombre);
        parser.mensajes.add("Definición de BD: " + nombre);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("definicionDB",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // storeDecl ::= STORE AT STRING_LITERAL PTCOMA 
            {
              String RESULT =null;
		int rutaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int rutaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String ruta = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
        System.out.println("Ruta de persistencia: " + ruta);
        parser.mensajes.add("Ruta de la BD: " + ruta);
        //para crear la ruta
        RESULT = ruta;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("storeDecl",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // instruccionUse ::= USE ID PTCOMA 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 
        System.out.println("Usando base de datos: " + nombre);
        parser.mensajes.add("Usando base de datos: " + nombre); 
        //para crear la instrucción de use
        gestor.usarBaseDeDatos(nombre);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("instruccionUse",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // definicionTabla ::= TABLE ID LLAIZQ listaCamposTabla LLADER 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int camposleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int camposright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		List campos = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
        System.out.println("Definición de tabla: " + nombre);
        parser.mensajes.add("Definición de tabla: " + nombre); 
        gestor.crearTabla(nombre, campos);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("definicionTabla",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // listaCamposTabla ::= campo listaCamposTabla 
            {
              List RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Map.Entry c = (Map.Entry)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		List resto = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        List<Map.Entry<String,Object>> lista = new ArrayList<>();
        lista.add(c);
        lista.addAll(resto);
        RESULT = lista;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("listaCamposTabla",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // listaCamposTabla ::= campo 
            {
              List RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Map.Entry c = (Map.Entry)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        List<Map.Entry<String,Object>> lista = new ArrayList<>();
        lista.add(c);
        RESULT = lista;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("listaCamposTabla",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // campo ::= ID DOSPUNTOS tipoDato PTCOMA 
            {
              Map.Entry RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int tdleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int tdright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String td = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
        System.out.println("Campo: " + nombre + " Tipo: " + td);
        parser.mensajes.add("Campo: " + nombre + " Tipo: " + td); 
        RESULT = new AbstractMap.SimpleEntry<>(nombre, td);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("campo",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // tipoDato ::= INT 
            {
              String RESULT =null;
		 RESULT = "int"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipoDato",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // tipoDato ::= FLOAT 
            {
              String RESULT =null;
		 RESULT = "float"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipoDato",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // tipoDato ::= BOOL 
            {
              String RESULT =null;
		 RESULT = "bool"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipoDato",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // tipoDato ::= STRING 
            {
              String RESULT =null;
		 RESULT = "string"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipoDato",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipoDato ::= ARRAY 
            {
              String RESULT =null;
		 RESULT = "array"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipoDato",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipoDato ::= OBJECT 
            {
              String RESULT =null;
		 RESULT = "object"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipoDato",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipoDato ::= NULL 
            {
              String RESULT =null;
		 RESULT = "null"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipoDato",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // lectura ::= READ ID LLAIZQ cuerpoLectura LLADER PTCOMA 
            {
              List RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).value;
		int clleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int clright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		lecturaInfo cl = (lecturaInfo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		 
        System.out.println("Lectura de tabla: " + nombre); 
        parser.mensajes.add("Lectura de tabla: " + nombre); 
        //la función de lectura entra acá
        List<Map<String,Object>> resultado = gestor.leer(nombre, cl.campos, cl.campoFiltro, cl.operador, cl.valorFiltro);

        //mostrar en consola las lecturas
        for (Map<String,Object> fila : resultado) {
            System.out.println(fila);
        }

        //guardar el resultado en RESULT para poder usarlo en export
        RESULT = resultado;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lectura",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // cuerpoLectura ::= seccionCampos seccionFiltroRead 
            {
              lecturaInfo RESULT =null;
		int scleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int scright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		camposInfo sc = (camposInfo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int sfleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int sfright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		filtroInfo sf = (filtroInfo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        RESULT = new lecturaInfo(sc.campos, sf.campo, sf.operador, sf.valor);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("cuerpoLectura",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // cuerpoLectura ::= seccionCampos 
            {
              lecturaInfo RESULT =null;
		int scleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int scright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		camposInfo sc = (camposInfo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        RESULT = new lecturaInfo(sc.campos, null, null, null);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("cuerpoLectura",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // seccionCampos ::= FIELDS DOSPUNTOS listaCamposRead PTCOMA 
            {
              camposInfo RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		List lc = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
        System.out.println("Campos seleccionados: " + lc);
        parser.mensajes.add("Campos seleccionados: " + lc); 
        RESULT = new camposInfo(lc);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionCampos",12, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // listaCamposRead ::= ID MASCampos 
            {
              List RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		List resto = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        //metemos los campos necesarios en una lista
        List<String> campos = new ArrayList<>();
        campos.add(nombre);
        campos.addAll(resto);
        RESULT = campos;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("listaCamposRead",13, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // MASCampos ::= COMA ID MASCampos 
            {
              List RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		List resto = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        //metemos los campos que sean necesarios en una lista
        List<String> campos = new ArrayList<>();
        campos.add(nombre);
        campos.addAll(resto);
        RESULT = campos;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("MASCampos",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // MASCampos ::= 
            {
              List RESULT =null;
		
        //si está vacío, no retornamos nada
        RESULT = new ArrayList<String>();
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("MASCampos",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // seccionFiltroRead ::= FILTER DOSPUNTOS ID IGUAL valor PTCOMA 
            {
              filtroInfo RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String campo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = new filtroInfo(campo, "==", v); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionFiltroRead",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // seccionFiltroRead ::= FILTER DOSPUNTOS ID DIFERENTE valor PTCOMA 
            {
              filtroInfo RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String campo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = new filtroInfo(campo, "!=", v); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionFiltroRead",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // seccionFiltroRead ::= FILTER DOSPUNTOS ID MAYOR valor PTCOMA 
            {
              filtroInfo RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String campo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = new filtroInfo(campo, ">", v); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionFiltroRead",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // seccionFiltroRead ::= FILTER DOSPUNTOS ID MENOR valor PTCOMA 
            {
              filtroInfo RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String campo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = new filtroInfo(campo, "<", v); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionFiltroRead",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // seccionFiltroRead ::= FILTER DOSPUNTOS ID MAYORIGUAL valor PTCOMA 
            {
              filtroInfo RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String campo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = new filtroInfo(campo, ">=", v); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionFiltroRead",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // seccionFiltroRead ::= FILTER DOSPUNTOS ID MENORIGUAL valor PTCOMA 
            {
              filtroInfo RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String campo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = new filtroInfo(campo, "<=", v); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionFiltroRead",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // exportacion ::= EXPORT STRING_LITERAL PTCOMA 
            {
              Object RESULT =null;
		int nombreArchivoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int nombreArchivoright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String nombreArchivo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
        System.out.println("exportación de BD: " + nombreArchivo);
        parser.mensajes.add("Exportación de BD: " + nombreArchivo);  
        //exportamos usando la última lectura guardada en el gestor
        gestor.exportar(nombreArchivo);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("exportacion",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // insercion ::= ADD ID LLAIZQ listaAsignaciones LLADER PTCOMA 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).value;
		int camposleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int camposright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		List campos = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		 
        System.out.println("Agregar registro: " + nombre);
        parser.mensajes.add("Agregar registro: " + nombre);  
        // Creamos un mapa para la fila, para ver los valores que entran en determinada fila
        Map<String,Object> fila = new HashMap<>();
        for (Object obj : campos) {
            Map.Entry<String,Object> entry = (Map.Entry<String,Object>) obj;
            fila.put(entry.getKey(), entry.getValue());
        }
        //llamar al gestor para insertar una nueva fila
        gestor.insertarRegistro(nombre, fila);
     
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("insercion",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // listaAsignaciones ::= asignacion MASAsignaciones 
            {
              List RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Map.Entry a = (Map.Entry)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		List resto = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        //acumulamos los campos en una lista
        List<Map.Entry<String,Object>> lista = new ArrayList<>();
        lista.add(a);
        lista.addAll(resto);
        RESULT = lista;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("listaAsignaciones",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // MASAsignaciones ::= COMA asignacion MASAsignaciones 
            {
              List RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Map.Entry a = (Map.Entry)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		List resto = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        //metemos las asignaciones en una lista
        List<Map.Entry<String,Object>> campos = new ArrayList<>();
        campos.add(a);
        campos.addAll(resto);
        RESULT = campos;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("MASAsignaciones",19, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // MASAsignaciones ::= 
            {
              List RESULT =null;
		
        //si está vacío, no retornamos nada
        RESULT = new ArrayList<Map.Entry<String,Object>>();
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("MASAsignaciones",19, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // asignacion ::= ID DOSPUNTOS valor 
            {
              Map.Entry RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        System.out.println("Campo: " + a + " Valor: " + v); 
        //devolvemos un par campo-valor
        //Esta es la mínima forma para asignar algún valor
        RESULT = new AbstractMap.SimpleEntry<>(a, v);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("asignacion",20, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // valor ::= ENTERO 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = e; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // valor ::= DECIMAL 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = d; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // valor ::= STRING_LITERAL 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = s; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // valor ::= TRUE 
            {
              Object RESULT =null;
		 RESULT = "true"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // valor ::= FALSE 
            {
              Object RESULT =null;
		 RESULT = "false"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // valor ::= NULL 
            {
              Object RESULT =null;
		 RESULT = "null"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // valor ::= CORIZQ listaValores CORDER 
            {
              Object RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = l; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // valor ::= LLAIZQ listaAsignaciones LLADER 
            {
              Object RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		List o = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 
        //convertimos lista de asignaciones en un mapa
        Map<String,Object> obj = new HashMap<>();
        //recorremos la lista de asignaciones y la vamos metiendo dentro de obj
        for (Object item : o) {
            Map.Entry<String,Object> entry = (Map.Entry<String,Object>) item;
            obj.put(entry.getKey(), entry.getValue());
        }
        //retornamos el objeto obj completo
        RESULT = obj; 
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // listaValores ::= valor MASValores 
            {
              List RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		List resto = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        //metemos los valores en una lista
        List<Object> lista = new ArrayList<>();
        lista.add(v);
        lista.addAll(resto);
        RESULT = lista;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("listaValores",22, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // MASValores ::= COMA valor MASValores 
            {
              List RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		List resto = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        //metemos los valores adicionales en una lista
        List<Object> lista = new ArrayList<>();
        lista.add(v);
        lista.addAll(resto);
        RESULT = lista;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("MASValores",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // MASValores ::= 
            {
              List RESULT =null;
		
        //si está vacío, no retornamos nada
        RESULT = new ArrayList<Object>();
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("MASValores",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // actualizacion ::= UPDATE ID LLAIZQ cuerpoActualizacion LLADER PTCOMA 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).value;
		int cAleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int cAright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		actualizacionInfo cA = (actualizacionInfo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		 
        System.out.println("Actualización de tabla: " + nombre); 
        parser.mensajes.add("Actualización de la tabla: " + nombre);  
        //la función de actualizar entra acá
        List<Map<String,Object>> resultado = gestor.actualizar(nombre, cA.campos, cA.campoFiltro, cA.valorFiltro);

        //mostrar en consola los registros actualizados
        for (Map<String,Object> fila : resultado) {
            System.out.println(fila);
        }
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("actualizacion",24, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // cuerpoActualizacion ::= seccionCamposActualizar seccionFiltroActualizar 
            {
              actualizacionInfo RESULT =null;
		int scaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int scaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		List sca = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int sfaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int sfaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		filtroInfo sfa = (filtroInfo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = new actualizacionInfo(sca, sfa.campo, sfa.operador, sfa.valor); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("cuerpoActualizacion",25, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // cuerpoActualizacion ::= seccionCamposActualizar 
            {
              actualizacionInfo RESULT =null;
		int scaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int scaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		List sca = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = new actualizacionInfo(sca, null, null, null); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("cuerpoActualizacion",25, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // seccionCamposActualizar ::= SET DOSPUNTOS listaCamposActualizar PTCOMA 
            {
              List RESULT =null;
		int lcaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int lcaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		List lca = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
        System.out.println("Campos seleccionados para actualizar: " + lca);
        RESULT = lca;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionCamposActualizar",26, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // listaCamposActualizar ::= campoActualizar MASCamposACtualizar 
            {
              List RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Map.Entry a = (Map.Entry)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		List resto = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        //metemos los campos necesarios en una lista
        List<Map.Entry<String,Object>> campos = new ArrayList<>();
        campos.add(a);
        campos.addAll(resto);
        RESULT = campos;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("listaCamposActualizar",27, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // MASCamposACtualizar ::= COMA campoActualizar MASCamposACtualizar 
            {
              List RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Map.Entry c = (Map.Entry)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int restoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int restoright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		List resto = (List)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        //metemos los campos que sean necesarios en una lista
        List<Map.Entry<String,Object>> lista = new ArrayList<>();
        lista.add(c);
        lista.addAll(resto);
        RESULT = lista;
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("MASCamposACtualizar",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // MASCamposACtualizar ::= 
            {
              List RESULT =null;
		
        //si está vacío, no retornamos nada
        RESULT = new ArrayList<Map.Entry<String,Object>>();
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("MASCamposACtualizar",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // campoActualizar ::= ID IGUAL_SIMPLE valor 
            {
              Map.Entry RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        //este es un par de tipo campo-valor simple
        System.out.println("Actualizar campo: " + nombre + " = " + v);
        parser.mensajes.add("Actualizar campo: " + nombre + " = " + v);  
        RESULT = new AbstractMap.SimpleEntry<>(nombre, v);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("campoActualizar",29, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // seccionFiltroActualizar ::= FILTER DOSPUNTOS ID IGUAL valor PTCOMA 
            {
              filtroInfo RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String campo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = new filtroInfo(campo, "==", v); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionFiltroActualizar",30, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // seccionFiltroActualizar ::= FILTER DOSPUNTOS ID DIFERENTE valor PTCOMA 
            {
              filtroInfo RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String campo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = new filtroInfo(campo, "!=", v); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionFiltroActualizar",30, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // seccionFiltroActualizar ::= FILTER DOSPUNTOS ID MAYOR valor PTCOMA 
            {
              filtroInfo RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String campo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = new filtroInfo(campo, ">", v); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionFiltroActualizar",30, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // seccionFiltroActualizar ::= FILTER DOSPUNTOS ID MENOR valor PTCOMA 
            {
              filtroInfo RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String campo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = new filtroInfo(campo, "<", v); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionFiltroActualizar",30, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // seccionFiltroActualizar ::= FILTER DOSPUNTOS ID MAYORIGUAL valor PTCOMA 
            {
              filtroInfo RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String campo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = new filtroInfo(campo, ">=", v); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionFiltroActualizar",30, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // seccionFiltroActualizar ::= FILTER DOSPUNTOS ID MENORIGUAL valor PTCOMA 
            {
              filtroInfo RESULT =null;
		int campoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int camporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String campo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = new filtroInfo(campo, "<=", v); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seccionFiltroActualizar",30, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // eliminacion ::= CLEAR ID PTCOMA 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
        System.out.println("Eliminación de registros completos en tabla: " + nombre);
        parser.mensajes.add("Eliminación de registros completos en tabla: " + nombre); 
        //Llamamos al gestor para poder limpiar todos los registros de la tabla o rows
        gestor.limpiarTabla(nombre);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("eliminacion",31, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
              return CUP$Sintactico$do_action_part00000000(
                               CUP$Sintactico$act_num,
                               CUP$Sintactico$parser,
                               CUP$Sintactico$stack,
                               CUP$Sintactico$top);
    }
}

}
