/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Rony
 */
public class interfazInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfazInicial.class.getName());

    /**
     * Creates new form interfazInicial
     */
    public interfazInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        inputEli2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputEli = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputEli1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        inputEli3 = new javax.swing.JTextArea();
        crear_archivo_btn = new javax.swing.JButton();
        abrir_archivo_btn = new javax.swing.JButton();
        guardar_archivo_btn = new javax.swing.JButton();
        ejecutar_btn = new javax.swing.JButton();
        tokens_btn = new javax.swing.JButton();
        errores_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        inputEli2.setColumns(20);
        inputEli2.setRows(5);
        jScrollPane3.setViewportView(inputEli2);

        jButton4.setText("Guardar archivo");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton7.setText("Reporte tokens");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputEli.setColumns(20);
        inputEli.setRows(5);
        jScrollPane1.setViewportView(inputEli);

        inputEli1.setColumns(20);
        inputEli1.setRows(5);
        jScrollPane2.setViewportView(inputEli1);

        inputEli3.setColumns(20);
        inputEli3.setRows(5);
        jScrollPane4.setViewportView(inputEli3);

        crear_archivo_btn.setBackground(new java.awt.Color(255, 255, 204));
        crear_archivo_btn.setText("Crear archivo");

        abrir_archivo_btn.setBackground(new java.awt.Color(255, 255, 204));
        abrir_archivo_btn.setText("Abrir archivo");
        abrir_archivo_btn.addActionListener(this::abrir_archivo_btnActionPerformed);

        guardar_archivo_btn.setBackground(new java.awt.Color(255, 255, 204));
        guardar_archivo_btn.setText("Guardar archivo");
        guardar_archivo_btn.addActionListener(this::guardar_archivo_btnActionPerformed);

        ejecutar_btn.setBackground(new java.awt.Color(102, 255, 204));
        ejecutar_btn.setText("Ejecutar");
        ejecutar_btn.addActionListener(this::ejecutar_btnActionPerformed);

        tokens_btn.setBackground(new java.awt.Color(204, 204, 255));
        tokens_btn.setText("Reporte tokens");
        tokens_btn.addActionListener(this::tokens_btnActionPerformed);

        errores_btn.setBackground(new java.awt.Color(204, 204, 255));
        errores_btn.setText("Reporte errores");
        errores_btn.addActionListener(this::errores_btnActionPerformed);

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IDE  - ILE language - Saint Charles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crear_archivo_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abrir_archivo_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardar_archivo_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ejecutar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tokens_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errores_btn))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(594, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear_archivo_btn)
                    .addComponent(abrir_archivo_btn)
                    .addComponent(guardar_archivo_btn)
                    .addComponent(ejecutar_btn)
                    .addComponent(tokens_btn)
                    .addComponent(errores_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                .addGap(14, 14, 14))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrir_archivo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrir_archivo_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrir_archivo_btnActionPerformed

    private void guardar_archivo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_archivo_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardar_archivo_btnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ejecutar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutar_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejecutar_btnActionPerformed

    private void tokens_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokens_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tokens_btnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void errores_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errores_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errores_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfazInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton abrir_archivo_btn;
    public javax.swing.JButton crear_archivo_btn;
    public javax.swing.JButton ejecutar_btn;
    public javax.swing.JButton errores_btn;
    public javax.swing.JButton guardar_archivo_btn;
    public javax.swing.JTextArea inputEli;
    public javax.swing.JTextArea inputEli1;
    public javax.swing.JTextArea inputEli2;
    public javax.swing.JTextArea inputEli3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JButton tokens_btn;
    // End of variables declaration//GEN-END:variables
}
