/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Rony
 */
public class interfazInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfazInicial.class.getName());

    /**
     * Creates new form interfazInicial
     */
    public interfazInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        inputEli2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputEli = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        entrada_programa = new javax.swing.JTextArea();
        crear_archivo_btn = new javax.swing.JButton();
        abrir_archivo_btn = new javax.swing.JButton();
        guardar_archivo_btn = new javax.swing.JButton();
        ejecutar_btn = new javax.swing.JButton();
        tokens_btn = new javax.swing.JButton();
        errores_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaErrores = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaTokens = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        inputEli2.setColumns(20);
        inputEli2.setRows(5);
        jScrollPane3.setViewportView(inputEli2);

        jButton4.setText("Guardar archivo");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton7.setText("Reporte tokens");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputEli.setColumns(20);
        inputEli.setRows(5);
        jScrollPane1.setViewportView(inputEli);

        entrada_programa.setColumns(20);
        entrada_programa.setRows(5);
        jScrollPane2.setViewportView(entrada_programa);

        crear_archivo_btn.setBackground(new java.awt.Color(255, 255, 204));
        crear_archivo_btn.setText("Crear archivo");

        abrir_archivo_btn.setBackground(new java.awt.Color(255, 255, 204));
        abrir_archivo_btn.setText("Abrir archivo");
        abrir_archivo_btn.addActionListener(this::abrir_archivo_btnActionPerformed);

        guardar_archivo_btn.setBackground(new java.awt.Color(255, 255, 204));
        guardar_archivo_btn.setText("Guardar archivo");
        guardar_archivo_btn.addActionListener(this::guardar_archivo_btnActionPerformed);

        ejecutar_btn.setBackground(new java.awt.Color(102, 255, 204));
        ejecutar_btn.setText("Ejecutar");
        ejecutar_btn.addActionListener(this::ejecutar_btnActionPerformed);

        tokens_btn.setBackground(new java.awt.Color(204, 204, 255));
        tokens_btn.setText("Reporte tokens");
        tokens_btn.addActionListener(this::tokens_btnActionPerformed);

        errores_btn.setBackground(new java.awt.Color(204, 204, 255));
        errores_btn.setText("Reporte errores");
        errores_btn.addActionListener(this::errores_btnActionPerformed);

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Salida:");

        tablaErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Tipo", "Descripción", "Línea", "Columna"
            }
        ));
        jScrollPane5.setViewportView(tablaErrores);

        tablaTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Lexema", "Tipo", "Línea", "Columna"
            }
        ));
        jScrollPane6.setViewportView(tablaTokens);

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("IDE  - ILE language - Saint Charles");

        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Entrada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(crear_archivo_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abrir_archivo_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guardar_archivo_btn))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(ejecutar_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tokens_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(errores_btn))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(636, 636, 636)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(314, 314, 314)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear_archivo_btn)
                    .addComponent(abrir_archivo_btn)
                    .addComponent(guardar_archivo_btn)
                    .addComponent(ejecutar_btn)
                    .addComponent(tokens_btn)
                    .addComponent(errores_btn))
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addGap(474, 474, 474)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrir_archivo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrir_archivo_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrir_archivo_btnActionPerformed

    private void guardar_archivo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_archivo_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardar_archivo_btnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ejecutar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutar_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejecutar_btnActionPerformed

    private void tokens_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokens_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tokens_btnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void errores_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errores_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errores_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfazInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton abrir_archivo_btn;
    public javax.swing.JButton crear_archivo_btn;
    public javax.swing.JButton ejecutar_btn;
    public javax.swing.JTextArea entrada_programa;
    public javax.swing.JButton errores_btn;
    public javax.swing.JButton guardar_archivo_btn;
    public javax.swing.JTextArea inputEli;
    public javax.swing.JTextArea inputEli2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTable tablaErrores;
    public javax.swing.JTable tablaTokens;
    public javax.swing.JButton tokens_btn;
    // End of variables declaration//GEN-END:variables
}
